// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyOQBQ0ijzMZU42Bw5pdesPZAtfC3D3i0',
    appId: '1:302266171798:web:67c720dbb8e5e809759db7',
    messagingSenderId: '302266171798',
    projectId: 'campusmarketplace-19060',
    authDomain: 'campusmarketplace-19060.firebaseapp.com',
    storageBucket: 'campusmarketplace-19060.firebasestorage.app',
    measurementId: 'G-LFCMG6BD0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBue0q8KwI8RFPr9rtv3zyQN6BYpMFRUdI',
    appId: '1:302266171798:android:5857ff71e0d18181759db7',
    messagingSenderId: '302266171798',
    projectId: 'campusmarketplace-19060',
    storageBucket: 'campusmarketplace-19060.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFed7PjOSrOWzWCmGM9XYeqMj5P-8ps7A',
    appId: '1:302266171798:ios:58c39cbc6fb6b483759db7',
    messagingSenderId: '302266171798',
    projectId: 'campusmarketplace-19060',
    storageBucket: 'campusmarketplace-19060.firebasestorage.app',
    iosClientId: '302266171798-00cgp3qmh5he3m2jne0i08tgasf1aard.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusMarketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFed7PjOSrOWzWCmGM9XYeqMj5P-8ps7A',
    appId: '1:302266171798:ios:58c39cbc6fb6b483759db7',
    messagingSenderId: '302266171798',
    projectId: 'campusmarketplace-19060',
    storageBucket: 'campusmarketplace-19060.firebasestorage.app',
    iosClientId: '302266171798-00cgp3qmh5he3m2jne0i08tgasf1aard.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusMarketplace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyOQBQ0ijzMZU42Bw5pdesPZAtfC3D3i0',
    appId: '1:302266171798:web:e12c0a42939063a2759db7',
    messagingSenderId: '302266171798',
    projectId: 'campusmarketplace-19060',
    authDomain: 'campusmarketplace-19060.firebaseapp.com',
    storageBucket: 'campusmarketplace-19060.firebasestorage.app',
    measurementId: 'G-53GJ4EVVSN',
  );

}